import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { TopBarComponent } from "@/components/top-bar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-slate-50 ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TopBarComponent />
        <div
          className="relative"
        >
          {/* Show what page the user is on */}
          <div className="container mx-auto flex justify-between">
            <h3 className="text-xl py-4 font-medium">
              Dashboard
            </h3>
            
          </div>
          {children}</div>
      </body>
    </html>
  );
}
