create table
  public.i_mechanics (
    id serial not null,
    name text not null,
    specialization text not null,
    constraint mechanics_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.i_maintenance_groups (
    created_at timestamp with time zone not null default now(),
    name text not null default 'Group'::text,
    id integer generated by default as identity not null,
    constraint i_maintenance_groups_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.i_maintenance_plans (
    id serial not null,
    planned_date timestamp with time zone not null,
    mold_id integer not null,
    maintenance_type character varying(20) not null,
    description text not null,
    assigned_to integer not null,
    status character varying(20) null default 'Planned'::character varying,
    maintenance_action text null,
    group_id integer null,
    constraint maintenance_plans_pkey primary key (id),
    constraint fk_assigned_to foreign key (assigned_to) references i_mechanics (id),
    constraint i_maintenance_plans_group_id_fkey foreign key (group_id) references i_maintenance_groups (id) on delete set null,
    constraint maintenance_plans_maintenance_type_check check (
      (
        (maintenance_type)::text = any (
          (
            array[
              'Preventative'::character varying,
              'Corrective'::character varying
            ]
          )::text[]
        )
      )
    ),
    constraint maintenance_plans_status_check check (
      (
        (status)::text = any (
          (
            array[
              'Planned'::character varying,
              'Busy'::character varying,
              'Finished'::character varying
            ]
          )::text[]
        )
      )
    )
  ) tablespace pg_default;
